version: "2"
services:
  gate-sql:
    image: mysql:5.7
    volumes:
      - ${PWD}/data:/var/lib/mysql
    environment:
      - MYSQL_USER=gate
      - MYSQL_PASSWORD=gate
    restart: always

  gate-redis:
    image: redis:5-alpine
    restart: always

  gate:
    image: gate
    ports:
      - "3000:3000"
    depends_on:
      - gate-sql
      - gate-redis
    env_file:
      - .env
    command: sh ./run.sh
    restart: always
