#!/bin/bash

if [[ $# -lt 1 ]]; then
  echo "$0 <user-name>"
  exit 1
fi

cd /etc/openvpn/keys
cp /opt/vpnkeys/$1.tar.gz ./
tar -xf $1.tar.gz
rm $1.ovpn
touch $1.ovpn
CA=$(cat /etc/openvpn/server/easy-rsa/pki/ca.crt)
CERT=$(cat /etc/openvpn/server/easy-rsa/pki/issued/$1.crt)
KEY=$(cat /etc/openvpn/server/easy-rsa/pki/private/$1.key)
TA=$(cat /etc/openvpn/server/ta.key)
cat > /etc/openvpn/keys/$1.ovpn <<EOF
client
dev tun
proto udp
remote <<your server name>> 1194
resolv-retry infinite
nobind
persist-key
persist-tun
comp-lzo
verb 3
remote-cert-tls server
auth SHA512
cipher AES-256-CBC
setenv opt block-outside-dns
key-direction 1
tun-mtu 1400
mssfix 1400
route 10.8.0.0 255.255.255.0
route 10.181.131.0 255.255.255.0
<ca>
$CA
</ca>
<cert>
$CERT
</cert>
<key>
$KEY
</key>
<tls-auth>
$TA
</tls-auth>

EOF

tar zcf $1.tar.gz $1.ovpn
chmod 0600 $1.tar.gz

mkdir -p  /opt/vpnkeys/
cp $1.tar.gz /opt/vpnkeys/
rm $1.*
